language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: slixes
    token:
      secure: fxu0J3iaOFjRPWHEEsg7zBbQQdv/bCY/dKIiTTP/RU70x2oBlqc0iNaaIDOxF+1ZO/4pqvnHeIaPLleCtay4XfsZACn6VYdcW6/pRu+k/NMInmnU/uDfJ8qFJyKWTS4DBvdh6yWTgkMMwlzyvvMtC5H/iOBxgW3eHcHdf5Rn815CQ5FdRjXWevsXNx2+7s7XMB1hsZsKoZ+tq70JetJzNoIsMdKedBBrfwUtB4JRCbiw7s5sDw8zVoBb8JxiW2wUs7+WsI1eo9C29u4proXzqM2g6/w/IiBrCwkJQNC6ZdGzsR7zN7OLyUMckfdzC/lyCxf/hxe09A41VYigW4Yjqrhq/tCQIeBdluFnwg8say0y55HacGSt3YzuDsS1cs5VrgkJtJJU5YP72LogqDgTguIVD2pHnWt5I9Al9emt4yyoSmi9y1lCYMt3oPFydZk37dMITQjTviRkEtEhKqARSsr4hECMzY0HRSxDR2Q3pBWWFy75bT5wFxtTJPk7ZEfKwzVs/pd6dc9Tam4+mb87nuvR6Im2wPGVO0xQW0pUr/J9hSj3oXJ3OmsSEkc0jvFaXZzFUM8l+hdUUJ0jLlrH6+VOPXXJmvduslyTDQNRX5iaOTcqQ7oVWtzsSbwJPNtKCTzWxeDQdwJUoeIr+shC0+4kfR2yBkK6UavBGZnWmCc=
    branches:
    - master
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.login=zYJ7vdsNcIF0JRnmXKCQiK5kp31vi2uNDW/g22Bv+ohCEK+bzJAJ4PslFiYV7+JacSw43GGzNpBS6/A4d4LXYrB9OY/aJ9zG6q/SejVGWTN8GdXcxuUw0FhYxE3qmKFKEzQmnrGayHegi1JW8THXttYysBjn+yT3sMaUAQEJKlxQ16qCTovUB4onmSGcmJn9CSdXtt0AmP7wiTqzngqKG6HMaTApSy5ATDWSXb8eU/Qud+Yoayk6VJ+o14nrNqQ7oUG2OggdRsTZ1cBYBsRvqpsL+VlcyJXSrN4SGvV0+poPzyNqkfCx/GokEewij7cZ9OmfbFXS8tU1Pnj25X/JLjL48h348X7DgEDkG0wFroZKjb2b3GTrtGvj6ezfb1p7Piv0RqwKq4oX+YwiP/PbkCMB+D77VapSb9YM+vsJ6RkKht/u05IzdChAttRZm3/t9rwHr8iG4BvOftmBe2VV4Uxj5J8qFI+ncSJQst7Zf+NuXtxcCOJBGJaqwBe7OncwqEbdEaC2lamqTjNjPU9wtQ+ae7e68QniuHbbM4vAPv/uSwIPZXudvY7+ttdrMAnzHfvC+PBvG9mAB/2cy//Cu1y1M2Q38cn6P14PBqXHnzesdsuJqBujG0/jRG0gV8Oy8s1TXXzB20Zerl+BvJ7GZZYlim8vAdOe7Vm2LH2y9oo=
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
    secure: zYJ7vdsNcIF0JRnmXKCQiK5kp31vi2uNDW/g22Bv+ohCEK+bzJAJ4PslFiYV7+JacSw43GGzNpBS6/A4d4LXYrB9OY/aJ9zG6q/SejVGWTN8GdXcxuUw0FhYxE3qmKFKEzQmnrGayHegi1JW8THXttYysBjn+yT3sMaUAQEJKlxQ16qCTovUB4onmSGcmJn9CSdXtt0AmP7wiTqzngqKG6HMaTApSy5ATDWSXb8eU/Qud+Yoayk6VJ+o14nrNqQ7oUG2OggdRsTZ1cBYBsRvqpsL+VlcyJXSrN4SGvV0+poPzyNqkfCx/GokEewij7cZ9OmfbFXS8tU1Pnj25X/JLjL48h348X7DgEDkG0wFroZKjb2b3GTrtGvj6ezfb1p7Piv0RqwKq4oX+YwiP/PbkCMB+D77VapSb9YM+vsJ6RkKht/u05IzdChAttRZm3/t9rwHr8iG4BvOftmBe2VV4Uxj5J8qFI+ncSJQst7Zf+NuXtxcCOJBGJaqwBe7OncwqEbdEaC2lamqTjNjPU9wtQ+ae7e68QniuHbbM4vAPv/uSwIPZXudvY7+ttdrMAnzHfvC+PBvG9mAB/2cy//Cu1y1M2Q38cn6P14PBqXHnzesdsuJqBujG0/jRG0gV8Oy8s1TXXzB20Zerl+BvJ7GZZYlim8vAdOe7Vm2LH2y9oo=
