language: java
sudo: false
install: true
addons:
  sonarcloud:
    organization: slixes
    token:
      secure: fxu0J3iaOFjRPWHEEsg7zBbQQdv/bCY/dKIiTTP/RU70x2oBlqc0iNaaIDOxF+1ZO/4pqvnHeIaPLleCtay4XfsZACn6VYdcW6/pRu+k/NMInmnU/uDfJ8qFJyKWTS4DBvdh6yWTgkMMwlzyvvMtC5H/iOBxgW3eHcHdf5Rn815CQ5FdRjXWevsXNx2+7s7XMB1hsZsKoZ+tq70JetJzNoIsMdKedBBrfwUtB4JRCbiw7s5sDw8zVoBb8JxiW2wUs7+WsI1eo9C29u4proXzqM2g6/w/IiBrCwkJQNC6ZdGzsR7zN7OLyUMckfdzC/lyCxf/hxe09A41VYigW4Yjqrhq/tCQIeBdluFnwg8say0y55HacGSt3YzuDsS1cs5VrgkJtJJU5YP72LogqDgTguIVD2pHnWt5I9Al9emt4yyoSmi9y1lCYMt3oPFydZk37dMITQjTviRkEtEhKqARSsr4hECMzY0HRSxDR2Q3pBWWFy75bT5wFxtTJPk7ZEfKwzVs/pd6dc9Tam4+mb87nuvR6Im2wPGVO0xQW0pUr/J9hSj3oXJ3OmsSEkc0jvFaXZzFUM8l+hdUUJ0jLlrH6+VOPXXJmvduslyTDQNRX5iaOTcqQ7oVWtzsSbwJPNtKCTzWxeDQdwJUoeIr+shC0+4kfR2yBkK6UavBGZnWmCc=
    branches:
    - master
jdk:
- oraclejdk8
script:
- mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
env:
  global:
  - secure: JKuxChIWBvQigRK20dxGvfS5mc+nYxYC+Q9iqKLd1ZsEt6Kh99wVKkQjqpbbC7+voyCADLJwMQ2t1xESvG/HMG1wLrdGvnk/HSl6+7d7RMgBFrvSxdi2Dyb90oKTulZLpUNYg0zHT8T0vCxzVdP3K6Srcm3OWF18vgiau5XysYh4a5emChCZ+0xf3cw/TIyr6olMtcPTLjVFykq1Q8yGx+xKWs1ofCUyg9LRu54omPZbzhkMAZc8BNyfPMauC57HAbmprpTWxvlV73lDED6htsP3um87WXKP/XDR/iiUu6X7ari8KQkeQ9WtUlHW8UjoyHNXAWPkKmVW3Qz4BtDnNJZDadJFCPJhpA46H9obxwxZM3X/YRH27VzMC0u2/gtdd/Th8aXiFo/kzHqFkfLPxuNSgGXTSdfVxCiBo6y6F3+Q6e+aNYWlFvK1YTExqnqBndtCji15delEO3zz5WzfMpo+T+0czo6S9EOdVfjJrXdfPUA/Pf6Sfl3+5WiwWMqLfZ5sX0V+9enCUQtf6QFxSegJRBXtnBVJOb5JlQgA5yVi+AYI3b6Y9k6Wkcw6zt2xtFKYq/G64ZvLJRz3NZs52/rHHHKRyMQ//vKF0NNYyOOg7TsRUYHEbUpMoZoYqSpsDgNsJOm+bhp+zXPm73EgmNcInvQPnWhDJc+K8yTI5k8=
  - secure: jxnc1Rq1p7B0UMhr3UBK7E9Ft/V6euSaPyWJIHST2hp2/prWq58a5H5fWKfTg5gogrooDK2ai8wj60YePw/QQHNAbz7UapePxy/WXv/gAQfyruDAl2Nm7VDX8nfUg303Xi/kJeKwykypewGnEJaZCRrXX03M6/CEggraK+3wvgCXclzNfyBsmyR45slAQcWbYcoBod2rB+7utoY7I1Pkw9eO0LlYyL9WQCkAQk08DaCpJqByc0ibnxjW4asKjk35jh0dHB9e6Zf/FowHxeXtpUwMX0/9OLN4fDfevHi9XcS/bW5io9LpFH25fkucLzoYadyqYAVlRmWC+fK+C/G516DvN0yEecdzUSsSQnJ371dNxmLY6EQSwIMm9vIlN4HfB7c7ChDFOlA8UmcpMmv88rwrtO7VtgurKR9+3O+jhYtv1UAynI/cGZlFShAm1+QFPVjqETxr6uH43IdbqX1VQevjuGvDV6p5LAPa5w5KIbj+ZgCyEFT1pjqdExt8W81IQaz/0NK5ogHPRO9Zy49M+AzTGaRIvazuQ6VWuU6ogsIjzYKwlyRgdQKe6cRaU+Rbex86SjPVSVnuF065W2UH1KG9cj6nn9pj/IlIQH0xMlOrRwTqXTzwOQdt3O5mQ3sxpTSLq90W1bmg9LItBYP+GvAj2x3krjQW+/FQ1t3kwK4=
