version: 2
jobs:
  build:
    working_directory: ~/slixes-parent
    docker:
      - image: circleci/openjdk:11
    steps:
      - checkout
      - restore_cache:
          key: slixes-parent-{{ checksum "pom.xml" }}
      - run: mvn dependency:go-offline
      - save_cache:
          paths:
            - ~/.m2
          key: slixes-parent-{{ checksum "pom.xml" }}
      - run: mvn verify
